language: objective-c
os: osx 
osx_image: xcode10.1

xcode_workspace: Manage Conky.xcworkspace
xcode_scheme: Manage Conky
xcode_destination: platform=macOS

before_install:
# install dependancies
  - brew tap Conky-for-macOS/homebrew-formulae
  - brew install freetype gettext lua imlib2 libircclient libmicrohttpd libical mysql librsvg pulseaudio #cairo-conky
  - brew link gettext --force

# setup xcode project
  - Tools/preheatProject.command
#  - cd ../../.. # return to project root
  - echo "$(pwd)"

script:
  - set -o pipefail && xcodebuild -workspace Manage\ Conky.xcworkspace -scheme Manage\ Conky -destination platform\=macOS build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
