language: objective-c
os: osx
osx_image: xcode10.1

xcode_workspace: Manage Conky.xcworkspace
xcode_scheme: Manage Conky
xcode_destination: platform=macOS

before_install:
# install dependancies
  - brew install freetype gettext lua imlib2
  - brew link gettext --force

# setup xcode project
  - cd ConkyX/conky-for-macOS/ManageConky
  - cmake .. -DWBUILD_WLAN=ON G Xcode
  - cd ../../..

script:
  - set -o pipefail && xcodebuild -workspace Manage\ Conky.xcworkspace -scheme Manage\ Conky -destination platform\=macOS build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty