language: objective-c
os: osx 
osx_image: xcode10.2

xcode_workspace: Manage Conky.xcworkspace
xcode_scheme: Manage Conky
xcode_destination: platform=macOS

before_install:
  - brew update # force a brew update because for some reason TravisCI likes not to update it.

  - gem install cocoapods -v '1.7.2'
  
  # install dependancies
  - brew tap Conky-for-macOS/homebrew-formulae
  - brew install --only-dependencies conky-all
  - brew link gettext --force
  - brew link --overwrite cairo-xlib --force

# setup xcode project
#  - Tools/preheatProject.command

script:
  - set -o pipefail && xcodebuild -workspace Manage\ Conky.xcworkspace -scheme Manage\ Conky -destination platform\=macOS build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
